/* This file contains the following english wordlist:
 *
 * oxford5k
 *    *Based* on the oxford 5k wordlist of commonly used words
 *    Some (but not all) homophones, similar meanings and potentially distressing words (when used
 *       as a description for your country) removed.
 *    items: 4199
 *    useful bits: 12 (need 4096 words)
 */

export const oxford5k = ["abandon", "ability", "able", "abolish", "about", "above", "abroad",
    "absent", "absolute", "absorb", "abstract", "absurd", "abundance",
    "academic", "academy", "accelerate", "accept", "acceptable", "acceptance", "access",
    "accessible", "accident", "accommodate", "accommodation", "accompany", "accomplish",
    "accordance", "according", "account", "accountable",
    "accountant", "accumulate", "accumulation", "accuracy", "accurate", "accusation", "accuse",
    "accused", "achieve", "achievement", "acid", "acknowledge", "acquire", "acquisition", "acre",
    "across", "act", "action", "activate", "activation", "active", "activist", "activity", "actor",
    "actress", "actual", "acute", "adapt", "adaptation", "add", "addiction", "addition",
    "additional", "address", "adequate", "adhere", "adjacent", "adjust", "adjustment", "administer",
    "admire", "admission", "admit",
    "adolescent", "adopt", "adoption", "adult", "advance", "advantage", "adventure",
    "adverse", "advertise", "advertisement", "advertising", "advise", "advocate",
    "aesthetic", "affair", "affection", "afford", "affordable", "afraid", "after",
    "aftermath", "afternoon", "afterwards", "again", "against", "age", "aged", "agency", "agenda",
    "agent", "aggression", "aggressive", "ago", "agree", "agreement", "agriculture",
    "ahead", "aid", "aim", "air", "aircraft", "airline", "airport", "alarm", "albeit",
    "album", "alert", "alien", "align", "alignment", "alike", "alive",
    "all", "allege", "allegedly", "alliance", "allocate", "allocation", "allow",
    "allowance", "ally", "almost", "alone", "along", "alongside", "already", "also", "alter",
    "alternative", "although", "altogether", "aluminium", "always", "amateur", "amazed", "amazing",
    "ambassador", "ambition", "ambitious", "ambulance", "amend", "amendment", "amid", "among",
    "amount", "amusing", "analogy", "analyse", "analyst", "ancestor", "anchor",
    "ancient", "and", "angel", "angle", "animal", "animation", "ankle",
    "anniversary", "announce", "announcement", "annoy", "annoyed", "annual",
    "anonymous", "another", "answer", "anticipate", "anxiety", "anxious", "any", "anybody",
    "anyone", "anything", "anyway", "anywhere", "apart", "apartment", "apologize", "apology", "app",
    "apparatus", "apparent", "appeal", "appealing", "appear", "appearance", "appetite", "applaud",
    "apple", "applicable", "applicant", "application", "apply", "appoint", "appointment",
    "appreciate", "appreciation", "approach", "appropriate", "approval", "approve", "approximately",
    "April", "arbitrary", "architect", "architectural", "architecture", "archive", "area", "arena",
    "arguably", "argue", "argument", "arise", "arm", "around", "arrange",
    "arrangement", "array", "arrest", "arrival", "arrive", "arrow", "art", "article", "articulate",
    "artificial", "artist", "artistic", "artwork", "as", "ash", "ashamed", "aside", "ask", "asleep",
    "aspect", "aspiration", "aspire", "assault", "assemble", "assert",
    "assertion", "assess", "assessment", "asset", "assign", "assignment", "assist",
    "assistant", "associate", "associated", "association", "assume", "assumption", "assurance",
    "assure", "astonishing", "asylum", "at", "athlete", "atmosphere", "attach",
    "attachment", "attack", "attain", "attempt", "attend", "attendance", "attention", "attitude",
    "attorney", "attract", "attraction", "attractive", "attribute", "audience", "audio",
    "audit", "August", "aunt", "authentic", "author", "authority", "authorize", "auto", "automatic",
    "autonomy", "autumn", "availability", "available", "average", "avoid", "await", "award",
    "aware", "awareness", "away", "awkward", "baby", "back", "backdrop", "background",
    "backing", "backup", "backwards", "bacteria", "badge", "bag", "bail", "bake", "balance",
    "balanced", "ball", "ballet", "balloon", "ballot", "ban", "banana", "band", "bank", "banner",
    "bar", "barely", "bargain", "barrel", "barrier", "base", "baseball", "based", "basement",
    "basic", "basis", "basket", "basketball", "bat", "bath", "bathroom", "battery",
    "battle", "battlefield", "bay", "be", "beach", "beam", "bean", "bear", "beast", "beat",
    "beautiful", "beauty", "because", "become", "bed", "bee", "beef", "beer", "before",
    "beg", "begin", "beginning", "behalf", "behave", "behaviour", "behind", "being", "belief",
    "believe", "bell", "belong", "beloved", "below", "belt", "bench", "benchmark", "bend",
    "beneath", "beneficial", "beneficiary", "benefit", "bent", "beside", "besides", "best", "bet",
    "better", "between", "beyond", "bias", "bicycle", "bid", "big", "bike", "bill",
    "billion", "bin", "bind", "biography", "biological", "biology", "bird", "birth", "birthday",
    "biscuit", "bishop", "bit", "bite", "bizarre", "blade", "blame", "blank",
    "blanket", "blast", "bleed", "blend", "bless", "blessing", "blind", "block", "blog", "blonde",
    "blood", "blow", "blue", "board", "boast", "boat", "body", "boil", "bold",
    "bond", "bone", "bonus", "book", "booking", "boom", "boost", "boot", "border", "born",
    "borrow", "boss", "both", "bother", "bottle", "bottom", "bounce", "bound", "boundary", "bow",
    "box", "boy", "boyfriend", "brain", "branch", "brand", "brave", "breach", "bread",
    "break", "breakdown", "breakfast", "breakthrough", "breast", "breath", "breathing",
    "breed", "brick", "bride", "bridge", "brief", "bright", "brilliant", "bring", "broad",
    "broadband", "broadcast", "broadcaster", "broadly", "broken", "brother", "brown", "browser",
    "brush", "bubble", "buddy", "budget", "buffer", "bug", "build", "building",
    "bulk", "bullet", "bunch", "burden", "bureaucracy", "burial", "burn", "burst", "bury", "bus",
    "bush", "business", "businessman", "busy", "but", "butter", "button", "by", "cabin", "cabinet",
    "cable", "cafe", "cake", "calculate", "calculation", "call", "calm", "camera", "camp",
    "campaign", "camping", "campus", "can", "canal", "cancel", "candidate", "candle",
    "cannot", "canvas", "cap", "capability", "capable", "capacity", "capital", "capitalism",
    "capitalist", "captain", "capture", "car", "carbon", "card", "care", "career", "careful",
    "careless", "cargo", "carpet", "carriage", "carrot", "carry", "cartoon", "carve", "case",
    "cash", "casino", "cast", "castle", "casual", "casualty", "cat", "catalogue", "catch",
    "category", "cater", "cattle", "cause", "caution", "cautious", "cave", "CD", "cease", "ceiling",
    "celebrate", "celebration", "celebrity", "cent", "central", "centre", "century",
    "ceremony", "certain", "certainty", "certificate", "chain", "chair", "chairman", "challenge",
    "challenging", "chamber", "champion", "championship", "chance", "change", "channel", "chaos",
    "chapter", "character", "charge", "charity", "charm",
    "charming", "chart", "charter", "chase", "chat", "check", "cheek", "cheer",
    "cheerful", "cheese", "chef", "chemical", "chemistry", "chest", "chicken", "chief", "child",
    "childhood", "chip", "chocolate", "choice", "choir", "choose", "chop", "chronic", "chunk",
    "church", "cigarette", "cinema", "circle", "circuit", "circulate", "circulation",
    "circumstance", "citizen", "citizenship", "city", "civic", "civil", "civilian",
    "civilization", "claim", "clarify", "clarity", "clash", "class", "classic", "classical",
    "classify", "classroom", "clause", "clean", "clear", "clerk", "clever",
    "click", "client", "cliff", "climate", "climb", "cling", "clinic", "clinical", "clip", "clock",
    "close", "closed", "closure", "cloth", "clothes", "clothing", "cloud", "club", "clue",
    "cluster", "coach", "coal", "coalition", "coast", "coastal", "coat", "cocktail", "code",
    "coffee", "cognitive", "coin", "coincide", "coincidence", "cold", "collaborate",
    "collapse", "colleague", "collect", "collection", "collective", "collector",
    "college", "collision", "colour", "colourful", "column",
    "columnist", "combination", "combine", "come", "comedy", "comfort", "comfortable",
    "comic", "command", "commander", "commence", "comment", "commentary", "commentator", "commerce",
    "commercial", "commission", "commissioner", "commit", "commitment", "committee", "commodity",
    "common", "communicate", "communication", "communist", "community", "companion", "company",
    "comparable", "compare", "compassion", "compel", "compelling", "compensate", "compensation",
    "compete", "competent", "competition", "competitive", "competitor", "compile",
    "complain", "complaint", "complement", "complete", "completion", "complex", "complexity",
    "compliance", "complicated", "comply", "component", "compose", "composer",
    "composition", "compound", "comprehensive", "comprise", "compromise", "compulsory", "compute",
    "computer", "conceal", "concede", "conceive", "concentrate", "concentration", "concept",
    "conception", "concern", "concerned", "concert", "concession", "conclude", "conclusion",
    "concrete", "condemn", "condition", "conduct", "confer", "conference", "confess", "confession",
    "confidence", "confident", "configuration", "confine", "confirm", "confirmation", "conflict",
    "confront", "confrontation", "confuse", "confused", "confusing", "confusion", "congratulate",
    "congregation", "congressional", "connect", "connected", "connection", "conquer", "conscience",
    "conscious", "consecutive", "consensus", "consent", "consequence",
    "conservation", "conservative", "conserve", "consider", "considerable", "consideration",
    "consist", "consistency", "consistent", "consolidate", "conspiracy", "constant", "constituency",
    "constitute", "constitution", "constraint", "construct", "construction",
    "consult", "consultant", "consume", "consumer", "consumption", "contact",
    "contain", "container", "contemplate", "contemporary", "contempt", "contend", "contender",
    "content", "contention", "contest", "context", "continent", "continually",
    "continue", "contract", "contractor", "contradiction", "contrary", "contrast",
    "contribute", "contribution", "contributor", "control", "controversial", "controversy",
    "convenience", "convenient", "convention", "conventional", "conversation", "conversion",
    "convert", "convey", "convict", "conviction", "convince", "convinced", "convincing", "cook",
    "cooker", "cooking", "cool", "cooperate", "cooperative", "coordinate", "coordination",
    "coordinator", "cop", "cope", "copper", "copy", "copyright", "core", "corner", "corporate",
    "corporation", "correct", "correction", "correctly", "correlate", "correlation", "correspond",
    "corridor",
    "costly", "costume", "cottage", "cotton", "could", "council", "counselling",
    "counsellor", "count", "counter", "counterpart", "countless", "country", "countryside",
    "county", "couple", "courage", "course", "court", "courtesy", "cousin", "cover",
    "coverage", "covered", "cow", "crack", "craft", "crash", "crawl", "crazy", "cream", "create",
    "creation", "creative", "creativity", "creator", "creature", "credibility", "credible",
    "credit", "creep", "crew", "crime", "crisis", "criterion", "critic", "critical",
    "criticism", "criticize", "critique", "crop", "cross", "crowd", "crowded", "crown", "crucial",
    "crude", "cruise", "crush", "cry", "crystal", "cue", "cult", "cultivate", "cultural",
    "culture", "cup", "cupboard", "cure", "curiosity", "curious", "curly", "currency", "current",
    "curriculum", "curtain", "curve", "curved", "custody", "custom", "customer", "cut", "cute",
    "cutting", "cycle", "cynical", "dad", "daily", "dairy", "dam", "damage", "damaging", "dance",
    "dancer", "dancing", "danger", "dangerous", "dare", "dark", "darkness", "data", "database",
    "date", "daughter", "dawn", "day", "deadline", "deadly", "deal", "dealer", "dear",
    "debate", "debris", "debt", "debut", "decade", "December", "decent", "decide",
    "decision", "decisive", "deck", "declaration", "declare", "decline", "decorate", "decoration",
    "decrease", "dedicated", "dedication", "deed", "deem", "deep", "default",
    "defence", "defend", "defender", "defensive", "deficiency", "deficit", "define", "definite",
    "definition", "defy", "degree", "delay", "delegate", "delegation", "delete", "deliberate",
    "delicate", "delicious", "delight", "delighted", "deliver", "delivery", "demand", "democracy",
    "democratic", "demonstrate", "demonstration", "denial", "denounce", "dense", "density",
    "dentist", "deny", "depart", "department", "departure", "depend", "dependence", "dependent",
    "depict", "deploy", "deployment", "deposit", "depressed", "depression", "deprive",
    "depth", "deputy", "derive", "descend", "describe", "description", "desert",
    "deserve", "design", "designate", "designer", "desirable", "desire", "desk", "desktop",
    "despite", "destination", "destroy", "destruction", "destructive", "detail",
    "detailed", "detain", "detect", "detection", "detective", "detention", "deteriorate",
    "determination", "determine", "determined", "devastate", "develop", "development", "device",
    "devil", "devise", "devote", "diagnose", "diagnosis", "diagram", "dialogue", "diamond", "diary",
    "dictate", "dictionary", "diet", "differ", "difference", "different",
    "differentiate", "difficult", "dig", "digital", "dignity", "dilemma", "dimension",
    "diminish", "dinner", "dip", "diplomat", "diplomatic", "direct", "direction", "director",
    "directory", "dirt", "disability", "disadvantage", "disagree",
    "disagreement", "disappear",
    "disaster", "disastrous", "disc", "discard", "discharge", "discipline", "disclose",
    "disclosure", "discount", "discourage", "discourse", "discover", "discovery", "discretion",
    "discuss", "discussion", "dish", "dishonest", "dislike", "dismiss",
    "dismissal", "disorder", "displace", "display", "disposal", "dispose", "dispute", "disrupt",
    "disruption", "dissolve", "distance", "distant", "distinct", "distinction", "distinctive",
    "distinguish", "distort", "distract", "distress", "distribute", "distribution", "district",
    "disturb", "disturbing", "dive", "diverse", "diversity", "divert", "divide", "divine",
    "division", "doctor", "doctrine", "document", "documentary",
    "documentation", "dog", "dollar", "domain", "domestic", "dominant", "dominate",
    "donate", "donation", "donor", "door", "dose", "dot", "double", "doubt", "down", "download",
    "downstairs", "downtown", "downwards", "dozen", "draft", "drag", "drain", "drama", "dramatic",
    "draw", "drawing", "dream", "dress", "dressed", "drift", "drink", "drive", "driver", "driving",
    "drop", "drought", "drown", "drug", "drum", "drunk", "dry", "dual", "dub", "due", "dull",
    "dump", "duration", "during", "dust", "duty", "DVD", "dynamic", "each", "eager",
    "ear", "early", "earn", "earnings", "earth", "earthquake", "ease", "easily",
    "easy", "eat", "echo", "ecological", "economic", "economics", "economist", "economy", "edge",
    "edit", "edition", "editor", "editorial", "educate", "educated", "education", "educational",
    "educator", "effect", "effective", "efficiency", "efficient", "effort", "egg",
    "ego", "eight", "eighteen", "eighty", "either", "elaborate", "elbow", "elderly", "elect",
    "election", "electoral", "electric", "electricity", "electronic",
    "elegant", "element", "elementary", "elephant", "elevate", "eleven", "eligible", "eliminate",
    "elite", "else", "elsewhere", "email", "embark",
    "embassy", "embed", "embody", "embrace", "emerge", "emergence", "emergency", "emission",
    "emotion", "emotional", "emphasis", "emphasize", "empire", "empirical", "employ", "employee",
    "employer", "employment", "empower", "empty", "enable", "enact", "encompass", "encounter",
    "encourage", "encouragement", "encouraging", "end", "endeavour", "ending", "endless", "endorse",
    "endorsement", "endure", "enemy", "energy", "enforce", "enforcement", "engage", "engaged",
    "engagement", "engaging", "engine", "engineer", "engineering", "enhance", "enjoy", "enjoyable",
    "enormous", "enough", "enquire", "enquiry", "enrich", "enrol", "ensue", "ensure", "enter",
    "enterprise", "entertain", "entertaining", "entertainment", "enthusiast",
    "enthusiastic", "entire", "entitle", "entity", "entrance", "entrepreneur", "entry", "envelope",
    "environment", "epidemic", "episode", "equal", "equality", "equation", "equip",
    "equipment", "equivalent", "era", "erect", "error", "erupt", "escalate", "escape", "especially",
    "essay", "essence", "essential", "establish", "establishment", "estate", "estimate", "eternal",
    "ethic", "ethical", "euro", "evacuate", "evaluate", "evaluation", "even", "evening",
    "event", "eventually", "ever", "every", "everybody", "everyday", "everyone", "everything",
    "everywhere", "evidence", "evident", "evoke", "evolution", "evolve",
    "exact", "exaggerate", "exam", "examination", "examine", "example", "exceed", "excellent",
    "except", "exception", "exceptional", "excess", "excessive", "exchange", "excited",
    "excitement", "exciting", "exclude", "exclusive", "excuse", "execute", "execution", "executive",
    "exercise", "exert", "exhibit", "exhibition", "exile", "exist", "existence", "exit", "exotic",
    "expand", "expansion", "expect", "expectation", "expected", "expedition", "expenditure",
    "expense", "expensive", "experience", "experiment", "experimental", "expert",
    "expertise", "expire", "explain", "explicit", "explode", "exploit", "exploitation",
    "exploration", "explore", "explosion", "explosive", "export", "expose", "exposure", "express",
    "expression", "extend", "extension", "extensive", "extent", "external", "extra", "extract",
    "extraordinary", "extreme", "extremist", "eye", "fabric", "fabulous", "face", "facilitate",
    "facility", "fact", "faction", "factor", "factory", "faculty", "fade", "fail",
    "fair", "fairness", "faith", "fall", "false", "fame", "familiar", "family", "famous",
    "fan", "fancy", "fantastic", "fantasy", "far", "farm", "farmer", "farming", "fascinating",
    "fashion", "fashionable", "fast", "fasten", "fat", "fatal", "fate", "father", "fault", "favour",
    "favourable", "favourite", "fear", "feat", "feather", "feature", "February", "federal", "fee",
    "feed", "feedback", "feel", "feeling", "fellow", "female", "fence", "festival",
    "fever", "few", "fibre", "fiction", "field", "fierce", "fifteen", "fifth", "fifty", "fight",
    "fighting", "figure", "file", "fill", "film", "filter", "final", "finance", "financial", "find",
    "finding", "fine", "finger", "finish", "fire", "firearm", "firefighter", "firework", "firm",
    "first", "fish", "fishing", "fit", "fitness", "five", "fix", "fixed", "fixture", "flag",
    "flame", "flash", "flat", "flavour", "flaw", "flawed", "flee", "fleet", "flexibility",
    "flexible", "flight", "float", "flood", "floor", "flourish", "flow", "flower", "flu", "fluid",
    "fly", "flying", "focus", "fold", "folding", "folk", "follow", "following", "fond", "food",
    "foot", "footage", "football", "for", "forbid", "force", "forecast", "foreign",
    "foreigner", "forest", "forever", "forge", "forget", "forgive", "fork", "form", "formal",
    "format", "formation", "former", "formula", "formulate", "forth", "forthcoming", "fortunate",
    "fortune", "forty", "forum", "forward", "fossil", "foster", "found", "foundation", "founder",
    "fourteen", "fraction", "fragile", "fragment", "frame", "framework",
    "franchise", "frankly", "free", "freedom", "freeze", "frequency", "frequent", "fresh",
    "Friday", "fridge", "friendly", "friendship", "frighten", "frightened", "frog",
    "from", "front", "frozen", "fruit", "frustrated", "frustrating", "frustration", "fry", "fuel",
    "fulfil", "full", "fun", "function", "functional", "fund", "fundamental", "funding",
    "fundraising", "funny", "fur", "furious", "furniture", "further", "furthermore",
    "future", "gain", "gallery", "gallon", "game", "gaming", "gang", "gap", "garage",
    "garden", "gas", "gate", "gather", "gathering", "gaze", "gear", "gene",
    "general", "generate", "generation", "generic", "generous", "genetic", "genius", "genocide",
    "genre", "gentle", "gentleman", "genuine", "geography", "gesture", "get", "ghost", "giant",
    "gift", "gig", "girl", "girlfriend", "give", "glad", "glance", "glass", "glimpse", "global",
    "globalization", "globe", "glorious", "glory", "glove", "go", "goal", "gold", "golden",
    "golf", "good", "goodbye", "goodness", "goods", "gorgeous", "govern", "governance",
    "government", "governor", "grab", "grace", "grade", "gradually", "graduate", "grain", "grand",
    "grandfather", "grandmother", "grandparent", "grant", "graphics", "grasp", "grass",
    "grateful", "grave", "gravity", "great", "green", "greenhouse", "greet", "grey", "grid",
    "grief", "grin", "grind", "grip", "grocery", "ground", "group", "grow", "growth",
    "guarantee", "guard", "guess", "guest", "guidance", "guide", "guideline",
    "guitar", "gut", "guy", "gym", "habit", "habitat", "hail", "hair", "half", "halfway",
    "hall", "halt", "hand", "handful", "handle", "handling", "handy", "hang", "happen", "happiness",
    "happy", "harassment", "harbour", "hard", "hardware", "harm", "harmful", "harmony", "harsh",
    "harvest", "hat", "haunt", "have", "hazard", "he", "head", "headache",
    "headline", "headquarters", "heal", "health", "healthcare", "healthy", "hear", "hearing",
    "heart", "heat", "heating", "heaven", "heavy", "height", "heighten", "helicopter",
    "hello", "helmet", "help", "helpful", "hence", "her", "herb", "heritage",
    "hero", "herself", "hesitate", "hey", "hidden", "hide", "hierarchy", "high", "highlight",
    "highway", "hilarious", "hill", "himself", "hint", "hip", "hire", "his", "historian",
    "historic", "history", "hit", "hobby", "hockey", "hold", "holiday", "hollow", "holy", "home",
    "homeland", "homeless", "homework", "honest", "honour", "hook", "hope", "hopeful", "horizon",
    "horn", "horse", "hospital", "host",
    "hot", "hotel", "hour", "house", "household", "housing", "how", "however", "huge", "human",
    "humanitarian", "humanity", "humble", "humorous", "humour", "hundred", "hunger", "hungry",
    "hunt", "hunting", "hurricane", "hurry", "hurt", "husband", "hydrogen", "hypothesis", "I",
    "ice", "icon", "ID", "idea", "ideal", "identical", "identity", "ideological",
    "if", "ignorance", "ignore", "ill", "illness", "illusion", "illustrate",
    "illustration", "image", "imagery", "imaginary", "imagination", "imagine", "immediate",
    "immense", "imminent", "immune", "impact", "impatient", "implement",
    "implication", "imply", "import", "important", "impose",
    "impossible", "impress", "impressed", "impression", "impressive", "imprison", "imprisonment",
    "improve", "improvement", "in", "inability", "inadequate", "inappropriate", "incentive", "inch",
    "incident", "inclined", "include", "included", "including", "inclusion", "income",
    "incorporate", "incorrect", "increase", "incredible", "incur", "indeed", "independence",
    "independent", "index", "indicate", "indication", "indicator", "indictment", "indigenous",
    "indirect", "individual", "indoor", "induce", "indulge", "industrial", "industry",
    "inevitable", "infant", "infect", "infection", "infer", "inflation", "inflict",
    "influence", "influential", "info", "inform", "informal", "information",
    "ingredient", "inhabitant", "inherent", "inherit", "inhibit", "initial", "initiate",
    "initiative", "inject", "injection", "injure", "injured", "injury", "injustice", "ink",
    "inmate", "inner", "innocent", "innovation", "innovative", "input", "insect", "insert",
    "insertion", "inside", "insider", "insight", "insist", "inspect", "inspection", "inspector",
    "inspiration", "inspire", "install", "installation", "instance", "instant", "instead",
    "instinct", "institute", "institution", "institutional", "instruct", "instruction",
    "instructor", "instrument", "instrumental", "insufficient", "insurance", "intact",
    "intake", "integral", "integrate", "integrated", "integration", "integrity", "intellectual",
    "intelligent", "intend", "intended", "intense", "intensify", "intensity",
    "intensive", "intent", "intention", "interact", "interaction", "interactive", "interest",
    "interested", "interesting", "interface", "interfere", "interference", "interim", "interior",
    "intermediate", "internal", "international", "internet", "interpret",
    "interrupt", "interval", "intervene", "intervention", "interview", "intimate", "into",
    "intriguing", "introduce", "introduction", "invade", "invasion", "invent", "invention",
    "invest", "investigate", "investigation", "investigator", "investment", "investor", "invisible",
    "invitation", "invite", "invoke", "involve", "involved", "involvement", "iron", "ironic",
    "irony", "irrelevant", "island", "isolate", "isolated", "isolation", "issue", "it", "item",
    "its", "itself", "jacket", "jail", "jam", "January", "jazz", "jeans", "jet", "jewellery", "job",
    "join", "joint", "joke", "journal", "journalism", "journalist", "journey", "joy", "judge",
    "judgement", "judicial", "juice", "July", "jump", "junction", "June", "junior", "jurisdiction",
    "jury", "just", "justice", "justification", "justify", "keen", "keep", "key", "keyboard",
    "kick", "kid", "kidnap", "kidney", "kilometre", "kind", "king", "kingdom",
    "kiss", "kit", "kitchen", "knee", "knife", "knock", "knowledge", "lab", "label", "laboratory",
    "labour", "lack", "lad", "ladder", "lady", "lake", "lamp", "land", "landing", "landlord",
    "landmark", "landscape", "lane", "language", "lap", "laptop", "large", "laser", "last", "late",
    "later", "latest", "latter", "laugh", "laughter", "launch", "law", "lawn", "lawsuit", "lawyer",
    "lay", "layer", "layout", "lazy", "lead", "leader", "leadership", "leading", "leaf", "leaflet",
    "league", "leak", "lean", "leap", "learn", "learning", "least", "leather", "leave", "lecture",
    "left", "leg", "legacy", "legal", "legend", "legendary", "legislation", "legislative",
    "legislature", "legitimate", "leisure", "lemon", "lend", "length", "lengthy", "lens",
    "less", "lesser", "lesson", "let", "letter", "level", "liable", "liberal",
    "liberation", "liberty", "library", "license", "lie", "life", "lifelong", "lifestyle",
    "lifetime", "lift", "light", "lighting", "like", "likelihood", "likewise", "limb", "limit",
    "limitation", "limited", "line", "linear", "linger", "link", "lion", "lip", "liquid", "list",
    "listen", "listener", "listing", "literacy", "literature", "litre", "litter", "little", "live",
    "lively", "liver", "living", "load", "loan", "lobby", "local", "locate", "located", "location",
    "lock", "log", "logic", "logical", "logo", "lonely", "long", "look", "loom", "loop",
    "lord", "lorry", "lose", "loss", "lost", "lot", "lottery", "loud", "love", "low", "lower",
    "loyal", "loyalty", "lucky", "lunch", "lung", "luxury", "lyric", "machine", "machinery",
    "magazine", "magic", "magical", "magistrate", "magnetic", "magnificent", "magnitude",
    "mail", "main", "mainland", "mainly", "mainstream", "maintain", "maintenance", "major",
    "majority", "make", "making", "man", "manage", "management", "manager", "mandate",
    "mandatory", "manifest", "manipulate", "manipulation", "manner", "manufacture", "manufacturing",
    "manuscript", "many", "map", "marathon", "march", "margin", "marginal", "marine", "mark",
    "marker", "market", "marketing", "marketplace", "marriage", "married", "marry", "martial",
    "mask", "mass", "massacre", "massive", "master", "match", "matching", "mate", "material",
    "mathematical", "mathematics", "maths", "matter", "mature", "maximize", "maximum", "may",
    "maybe", "mayor", "me", "meal", "mean", "meaning", "meaningful", "means", "meantime",
    "meanwhile", "measure", "measurement", "meat", "mechanic", "mechanical", "mechanism", "medal",
    "media", "medical", "medication", "medicine", "medieval", "meditation", "medium", "meeting",
    "melody", "melt", "member", "membership", "memo", "memoir", "memorable", "memorial", "memory",
    "mental", "mention", "mentor", "menu", "merchant", "mercy", "mere", "merely", "merge", "merger",
    "merit", "mess", "message", "metal", "metaphor", "method", "methodology", "metre", "middle",
    "midnight", "midst", "might", "migration", "mild", "mile",
    "milk", "mill", "million", "mind", "mine", "miner", "mineral", "minimal", "minimize", "minimum",
    "mining", "minister", "ministry", "minute", "miracle", "mirror",
    "misery", "miss", "missing", "mission", "mix",
    "mixed", "mixture", "mob", "mobile", "mobility", "mobilize", "mode", "model", "moderate",
    "modern", "modest", "modification", "modify", "moment", "momentum", "Monday", "money",
    "monitor", "monk", "monopoly", "monster", "month", "monument", "mood", "moon",
    "moral", "morality", "more", "moreover", "morning", "mortgage", "mosque", "most", "mother",
    "motion", "motivate", "motivation", "motive", "motor", "motorcycle", "motorist", "mount",
    "mountain", "mouse", "mouth", "move", "movement", "movie", "moving", "much", "mud", "multiply",
    "mum", "municipal", "murder", "muscle", "museum", "music", "musical", "musician", "must",
    "mutual", "my", "myself", "mysterious", "mystery", "myth", "nail", "name", "narrative",
    "narrow", "nation", "national", "nationwide", "native", "natural", "nature", "naval",
    "navigation", "near", "nearby", "nearly", "neat", "necessary", "necessity",
    "neck", "need", "needle", "negative", "neglect", "negotiate", "negotiation", "neighbour",
    "neighbourhood", "neighbouring", "neither", "nerve", "nervous", "nest", "net", "network",
    "neutral", "never", "nevertheless", "new", "news", "newsletter", "newspaper", "next", "nice",
    "niche", "night", "nightmare", "nine", "nineteen", "ninety", "no", "noble", "nobody", "nod",
    "noise", "noisy", "nominate", "nomination", "nominee", "none", "nonetheless", "nonsense",
    "noon", "nor", "norm", "normal", "north", "nose", "not", "notable", "notably",
    "note", "notebook", "nothing", "notice", "notify", "notion", "notorious", "novel", "novelist",
    "November", "now", "nowadays", "nowhere", "number", "numerous", "nurse", "nursery",
    "nursing", "nut", "nutrition", "obesity", "obey", "object", "objection", "objective",
    "obligation", "oblige", "observation", "observe", "observer", "obsess", "obsession", "obstacle",
    "obtain", "obvious", "occasion", "occasional", "occupation", "occupy", "occur", "occurrence",
    "ocean", "October", "odd", "off", "offence", "offend", "offer",
    "offering", "office", "officer", "official", "offspring", "often", "oil", "OK", "old",
    "on", "once", "one", "ongoing", "onion", "online", "only", "onto", "open", "opening", "openly",
    "opera", "operate", "operation", "operational", "operator", "opinion", "opponent",
    "opportunity", "oppose", "opposed", "opposite", "opposition", "optical", "optimism",
    "optimistic", "option", "oral", "orange", "orchestra", "order", "ordinary", "organ",
    "organic", "organization", "organize", "organized", "organizer",
    "orientation", "origin", "original", "originate", "other", "otherwise", "ought", "our", "ours",
    "ourselves", "out", "outbreak", "outcome", "outdoors", "outer", "outfit", "outing",
    "outlet", "outline", "outlook", "output", "outrage", "outside", "outsider", "outstanding",
    "oven", "over", "overall", "overcome", "overlook", "overnight", "overseas", "oversee",
    "overturn", "overwhelm", "overwhelming", "owe", "own", "owner", "ownership", "oxygen",
    "o’clock", "pace", "pack", "package", "packet", "pad", "page", "pain", "painful", "paint",
    "painter", "painting", "pair", "palace", "pale", "palm", "pan", "panel", "panic",
    "paper", "parade", "paragraph", "parallel", "parameter", "parent", "parental", "parish", "park",
    "parking", "parliament", "parliamentary", "part", "partial", "participant", "participate",
    "participation", "particular", "partly", "partner", "partnership", "party", "pass", "passage",
    "passenger", "passing", "passion", "passionate", "passive", "passport", "password", "past",
    "pastor", "patch", "patent", "path", "pathway", "patience", "patient", "patrol", "patron",
    "pattern", "pause", "pay", "payment", "peace", "peaceful", "peak", "peasant", "peculiar",
    "peer", "pen", "penalty", "pencil", "penny", "pension", "people", "pepper", "perceive",
    "percentage", "perception", "perfect", "perform", "performance", "perhaps", "period",
    "permanent", "permission", "permit", "persist", "persistent", "person", "personal",
    "personality", "perspective", "persuade", "pet", "petition", "phase",
    "phenomenon", "philosopher", "philosophical", "philosophy", "phone", "photo", "photographer",
    "photography", "phrase", "physical", "physics", "piano", "pick", "picture", "pig",
    "pile", "pill", "pilot", "pin", "pink", "pioneer", "pipe", "pipeline", "pirate", "pit", "pitch",
    "pity", "place", "placement", "plain", "plan", "planet", "planning", "plant", "plastic",
    "plate", "platform", "play", "player", "plea", "pleasant", "please", "pleasure", "pledge",
    "plenty", "plot", "plug", "plunge", "plus", "pocket", "poem", "poet", "poetry", "point",
    "pointed", "poison", "poisonous", "pole", "police", "policy", "polite", "politician",
    "politics", "pollution", "pond", "pool", "pop", "popular", "popularity", "population",
    "port", "portfolio", "portion", "portrait", "portray", "pose", "position", "positive",
    "possess", "possession", "possibility", "possible", "post", "poster", "postpone", "pot",
    "potato", "potential", "pound", "pour", "powder", "power", "powerful", "practical",
    "practice", "practitioner", "praise", "pray", "prayer", "preach", "precede", "precedent",
    "precious", "precise", "precision", "predecessor", "predict", "predictable",
    "prediction", "predominantly", "prefer", "preference", "pregnancy", "pregnant",
    "preliminary", "premier", "premise", "premium", "preparation", "prepare", "prepared",
    "prescribe", "prescription", "presence", "present", "presentation", "preservation", "preserve",
    "preside", "presidency", "president", "presidential", "press", "pressure", "prestigious",
    "presume", "pretend", "pretty", "prevail", "prevalence", "prevent", "prevention", "previous",
    "price", "pride", "priest", "primary", "prime", "prince", "princess",
    "principle", "print", "printer", "printing", "prior", "priority", "prison", "prisoner",
    "privacy", "private", "privatization", "privilege", "prize", "probability", "probable", "probe",
    "problem", "problematic", "procedure", "proceed", "proceedings", "proceeds", "process",
    "processing", "processor", "proclaim", "produce", "producer", "product", "production",
    "productive", "productivity", "profession", "professional", "professor", "profile", "profit",
    "profitable", "profound", "program", "programming", "progress", "progressive", "prohibit",
    "project", "projection", "prominent", "promise", "promising", "promote", "promotion", "prompt",
    "pronounce", "pronounced", "proof", "propaganda", "proper", "property", "proportion",
    "proposal", "propose", "proposition", "prosecute", "prosecution", "prosecutor", "prospect",
    "prospective", "prosperity", "protect", "protection", "protective", "protein", "protest",
    "protester", "protocol", "proud", "prove", "provide", "province", "provincial", "provision",
    "provoke", "psychiatric", "psychological", "psychologist", "psychology", "pub", "public",
    "publication", "publicity", "publish", "publishing", "pull", "pulse", "pump", "punch", "punish",
    "punishment", "punk", "pupil", "purchase", "pure", "purple", "purpose", "pursue", "pursuit",
    "push", "put", "puzzle", "qualification", "qualify", "quality", "quantity", "quarter", "queen",
    "query", "quest", "question", "queue", "quick", "quiet", "quit", "quite", "quota", "quotation",
    "quote", "race", "racial", "racing", "radar", "radiation", "radical", "radio", "rage", "raid",
    "rail", "rain", "raise", "rally", "random", "range", "rank", "ranking", "rapid", "rare", "rat",
    "rate", "rather", "rating", "ratio", "rational", "raw", "ray", "reach", "react", "reaction",
    "reader", "readily", "reading", "ready", "real", "realistic", "reality", "realization",
    "realize", "really", "realm", "rear", "reason", "reasonable", "reasoning", "reassure", "rebel",
    "rebellion", "rebuild", "recall", "receipt", "receive", "receiver", "recent", "reception",
    "recession", "recipe", "recipient", "reckon", "recognition", "recognize", "recommend",
    "record", "recording", "recount", "recover", "recovery",
    "recruit", "recruitment", "recycle", "red", "reduce", "reduction", "refer", "referee",
    "reference", "referendum", "reflect", "reflection", "reform", "refuge", "refusal",
    "refuse", "regain", "regard", "regardless", "regime", "region", "regional", "register",
    "registration", "regret", "regular", "regulate", "regulation", "regulator", "regulatory",
    "reject", "rejection", "relate", "related", "relation", "relationship",
    "relative", "relax", "relaxed", "relaxing", "release", "relevance", "relevant", "reliability",
    "reliable", "relief", "relieve", "relieved", "reluctant", "rely",
    "remain", "remainder", "remains", "remark", "remarkable", "remedy", "remember", "remind",
    "reminder", "remote", "removal", "remove", "render", "renew", "renowned", "rent", "rental",
    "repair", "repeat", "repeated", "replace", "replacement", "reply", "report", "reporter",
    "reporting", "represent", "reproduce", "reproduction",
    "republic", "reputation", "request", "require", "requirement", "rescue", "research",
    "researcher", "resemble", "reservation", "reserve", "reside", "resident",
    "residential", "residue", "resign", "resignation", "resist", "resistance", "resolution",
    "resolve", "resort", "resource", "respect", "respective", "respond", "response",
    "responsible", "rest", "restaurant", "restoration", "restore", "restraint",
    "restrict", "restriction", "result", "resume", "retail", "retain", "retire", "retired",
    "retirement", "retreat", "retrieve", "return", "reveal", "revelation", "revenue",
    "reverse", "review", "revise", "revision", "revival", "revive", "revolution", "revolutionary",
    "reward", "rhetoric", "rhythm", "rice", "rich", "rid", "ride", "rifle", "right",
    "ring", "riot", "rip", "rise", "risk", "risky", "ritual", "rival", "river", "road", "rob",
    "robbery", "robot", "robust", "rock", "rocket", "rod", "roll", "romance", "romantic", "roof",
    "room", "root", "rope", "rose", "rotate", "rotation", "rough", "round", "routine", "row",
    "royal", "rub", "rubber", "rugby", "rule", "ruling", "rumour", "run",
    "runner", "running", "rural", "rush", "sack", "sacred", "sacrifice", "sad", "safe", "safety",
    "sailing", "sailor", "saint", "sake", "salad", "salary", "sale", "salt", "same", "sample",
    "sanction", "sand", "sandwich", "satellite", "satisfaction", "satisfied", "satisfy", "Saturday",
    "sauce", "save", "saving", "say", "scale", "scan", "scandal", "scare", "scared", "scary",
    "scattered", "scenario", "scene", "sceptical", "schedule", "scheme", "scholar", "scholarship",
    "school", "science", "scientific", "scientist", "scope", "score", "scratch", "scream", "screen",
    "screening", "script", "scrutiny", "sculpture", "seal", "search", "season", "seat",
    "second", "secondary", "secret", "secretary", "section", "sector", "secular", "secure",
    "security", "see", "seed", "seek", "seem", "seemingly", "segment", "seize", "seldom", "select",
    "selection", "selective", "self", "sell", "seminar", "senator", "send", "senior", "sensation",
    "sense", "sensible", "sensitive", "sensitivity", "sentence", "sentiment", "separate",
    "separation", "September", "sequence", "serial", "series", "serious", "servant", "serve",
    "service", "session", "set", "setting", "settle", "settlement", "settler", "seven", "seventeen",
    "seventy", "several", "severe", "shade", "shadow", "shake", "shall", "shallow",
    "shape", "shaped", "share", "sharp", "shatter", "she", "shed", "sheep", "sheet", "shelf",
    "shell", "shelter", "shift", "shine", "shiny", "ship", "shirt", "shock", "shocking", "shoe",
    "shoot", "shooting", "shop", "shopping", "shore", "short", "shortage", "shot", "should",
    "shoulder", "shout", "show", "shower", "shrink", "shrug", "shut", "shy", "sibling", "sick",
    "side", "sigh", "sight", "sign", "signal", "signature", "significance", "significant",
    "silence", "silent", "silk", "silly", "silver", "similar", "similarity", "simple", "simulate",
    "simulation", "since", "sincere", "sing", "singer", "singing", "single", "sink", "sir",
    "sister", "sit", "situated", "situation", "six", "sixteen", "sixty", "size", "sketch", "ski",
    "skiing", "skill", "skilled", "skin", "skip", "skirt", "skull", "sky", "slam", "slap", "slash",
    "sleep", "slice", "slide", "slight", "slip", "slope", "slow", "small", "smart",
    "smartphone", "smell", "smile", "smoke", "smoking", "smooth", "snake", "snow", "so", "soap",
    "soccer", "social", "society", "sock", "soft", "software", "soil", "solar", "soldier", "solid",
    "solution", "solve", "some", "somebody", "someone", "something", "sometimes", "somewhat",
    "somewhere", "son", "song", "soon", "sorry", "sort", "soul", "sound", "soup", "source", "south",
    "space", "speak", "speaker", "special", "specialist", "species", "specific",
    "speech", "speed", "spell", "spelling", "spend", "spending", "spicy", "spider", "spirit",
    "spiritual", "split", "spoken", "sponsor", "spoon", "sport", "spot", "spread", "spring",
    "square", "stable", "stadium", "staff", "stage", "stamp", "stand", "standard", "star", "stare",
    "start", "state", "statement", "station", "statistic", "statue", "status", "stay", "steady",
    "steal", "steep", "step", "stick", "sticky", "stiff", "still", "stock", "stomach", "stone",
    "stop", "store", "storm", "story", "straight", "strange", "stranger", "strategy", "stream",
    "street", "strength", "stretch", "strict", "strike", "string", "strong", "structure",
    "struggle", "student", "studio", "study", "stuff", "stupid", "style", "subject", "submit",
    "substance", "succeed", "success", "successful", "such", "sudden", "suffer", "sugar", "suggest",
    "suggestion", "suit", "suitable", "summarize", "summary", "summer", "Sunday", "supermarket",
    "supply", "support", "supporter", "suppose", "sure", "surface", "surgery", "surprise",
    "surprising", "surround", "surrounding", "survey", "survive", "suspect", "swear",
    "sweater", "sweep", "sweet", "swim", "swimming", "switch", "symbol", "sympathy", "symptom",
    "system", "T-shirt", "table", "tablet", "tail", "take", "talent", "talented", "talk", "tall",
    "tank", "tape", "target", "task", "taste", "tax", "taxi", "tea", "teach", "teacher", "teaching",
    "team", "tear", "technical", "technique", "technology", "teenage", "teenager", "telephone",
    "television", "tell", "temperature", "temporary", "ten", "tend", "tennis", "tent", "term",
    "test", "text", "than", "thank", "thanks", "that", "the", "theatre", "theirs",
    "them", "theme", "themselves", "then", "theory", "therapy", "there", "therefore", "they",
    "thick", "thief", "thin", "thing", "think", "thinking", "third", "thirsty", "thirteen",
    "thirty", "this", "thought", "thousand", "threat", "threaten", "three", "throat",
    "through", "throughout", "throw", "Thursday", "thus", "ticket", "tidy", "tie", "tight", "till",
    "time", "tin", "tiny", "tip", "tired", "title", "today", "toe", "together", "tomato",
    "tomorrow", "tone", "tonight", "tool", "tooth", "top", "topic", "total", "touch",
    "tough", "tour", "tourism", "tourist", "towards", "towel", "tower", "town", "toy", "track",
    "trade", "tradition", "traffic", "train", "trainer", "training", "transfer", "transform",
    "transition", "translation", "transport", "travel", "traveller", "treatment", "tree", "trend",
    "trial", "trick", "trip", "tropical", "trouble", "trousers", "truck", "true", "trust", "truth",
    "try", "tube", "Tuesday", "tune", "tunnel", "turn", "TV", "twelve", "twenty", "twice", "twin",
    "two", "type", "typical", "ultimate", "umbrella", "unable", "uncle",
    "uncomfortable", "unconscious", "under", "underground", "understand", "unemployed",
    "unexpected", "unfair", "unfortunately", "uniform", "union", "unique", "unit",
    "united", "universe", "university", "unknown", "unless", "unlikely", "unnecessary", "until",
    "unusual", "up", "update", "upon", "upper", "upset", "upstairs", "upwards", "urban", "urge",
    "use", "useful", "user", "usual", "vacation", "valley", "value", "van", "vanish", "variation",
    "variety", "various", "vast", "vegetable", "vehicle", "vein", "venture", "venue",
    "verbal", "verdict", "verify", "verse", "version", "versus", "vertical", "very", "vessel",
    "veteran", "viable", "vibrant", "vicious", "victory", "video", "view", "viewer",
    "viewpoint", "village", "virtual", "virtue", "virus", "visa", "visible", "vision", "visit",
    "visual", "vital", "vitamin", "vocal", "voice", "volume", "volunteer", "vote", "vow",
    "vulnerable", "wage", "wait", "waiter", "wake", "walk", "wall", "wander", "want", "war", "ward",
    "warehouse", "warfare", "warm", "warming", "warn", "warning", "warrant", "warrior", "wash",
    "washing", "waste", "watch", "water", "wave", "way", "we", "weak", "weaken", "weakness",
    "wealth", "weapon", "weather", "weave", "web", "website", "wedding", "Wednesday",
    "weed", "weekend", "weekly", "weird", "welcome", "welfare", "well", "west", "western",
    "wet", "what", "whatever", "wheat", "wheel", "when", "whenever", "where", "wherever", "which",
    "while", "whip", "whisper", "who", "whoever", "whole", "whose", "why", "wide",
    "widely", "widen", "widespread", "widow", "width", "wife", "wild", "wildlife", "will",
    "willing", "win", "wind", "window", "wine", "wing", "winner", "winter", "wipe", "wire",
    "wisdom", "wise", "wish", "wit", "with", "withdraw", "within", "without", "witness", "woman",
    "wonder", "wonderful", "wood", "wool", "word", "work", "worker", "workforce", "working",
    "workout", "workplace", "workshop", "world", "worldwide", "worm", "worried", "worry",
    "worship", "worth", "worthwhile", "worthy", "wow", "wrap", "wrist", "writer",
    "writing", "written", "wrong", "yard", "year", "yell", "yellow", "yes", "yesterday", "yet",
    "yield", "you", "young", "your", "yourself", "youth", "zero", "zone"]
