export const includeWords = ["apollo", "hercules", "zeus", "atlas", "hermes", "mars", "saturn",
    "jupiter", "venus", "mercury", "pluto", "neptune", "violet", "indigo", "blue", "green",
    "yellow", "orange", "gold", "silver", "bronze", "iron", "sodium", "potassium", "magnesium",
    "calcium", "radium", "tin", "chromium", "zinc", "copper", "nickel", "cobalt", "odin", "thor",
    "loki", "basilisk", "centaur", "cyclops", "pegasus", "minotaur", "zodiac", "gemini", "lion",
    "scorpion", "aquarius", "capricorn", "goat", "voyager", "curiosity", "galileo", "grail",
    "hubble", "juno", "lunar", "solar", "shuttle", "viking", "electron", "photon", "neutron",
    "atom", "molecule", "euclid", "archimedes", "newton", "einstein", "darwin", "pascal", "tesla",
    "aristotle", "franklin", "babbage", "morse", "braille", "maxwell", "edison", "turing", "homer",
    "doyle", "shakespeare", "dante", "joyce", "byron", "milton", "voltaire", "huxley", "kipling",
    "shelley", "blake", "virgil", "auden", "keats", "beckett", "marlowe", "lawrence", "tennyson",
    "whitman", "yeats", "tolstoy", "beethoven", "vivaldi", "leonardo", "raphael", "michelangelo",
    "donatello", "genesis", "exodus", "camelot", "merlin", "grail", "backgammon", "checkers",
    "sudoku", "othello", "ludo", "monopoly", "alias", "labyrinth", "rummy", "mahjong", "mancala",
    "cribbage", "pontoon", "tag", "sardines", "conkers", "marbles", "tennis", "hopscotch", "limbo",
    "archery", "badminton", "volley", "cricket", "scooter", "surfing", "frisbee", "quidditch",
    "bouldering", "hiking", "judo", "karate", "ninja", "sumo", "fencing", "billiards", "snooker",
    "darts", "equestrian", "polo", "golf", "gymnastics", "juggling", "acrobatics", "skating",
    "triathlon", "decathalon", "marathon", "sprint", "hurdles", "bobsleigh", "toboggan", "hockey",
    "curling", "parkour", "walking", "omaha", "whist", "dominoes", "savior", "somehow", "turning",
    "romeo", "juliet",

    "briar", "macbeth", "boxer", "comet", "eureka", "excursion", "medusa", "hexagon",
    "pentagon", "virgo", "juniper", "omega",
    "prism", "portal", "rover", "utopia"

]

export const excludeWords = ["virus", "pregnant", "hunger", "clown", "ape", "genocide",
    "nonetheless", "north", "south", "east", "west", "acceptable", "acid", "activation", "adult",
    "adverse", "aesthetic", "albeit", "allege", "attorney", "auto", "bacteria", "battlefield",
    "bean", "believe", "besides", "blonde", "blood", "bottom", "boyfriend", "girlfriend", "breast",
    "bug", "bullet", "CD", "DVD", "chemical", "chronic", "cigarette", "come", "communist",
    "conscience", "convict", "countless", "countryside", "creep", "crude", "cult", "deadly",
    "democracy", "democratic", "dependence", "depression", "devil", "donkey", "app", "earring",
    "eliminate", "empire", "emission", "epidemic", "examination", "explode", "extremist", "faction",
    "false", "fatal", "fault", "finger", "firearm", "foreigner", "foreign", "frog", "grab",
    "harassment", "ID", "infection", "injure", "inmate", "insert", "intimate", "invade", "martial",
    "master", "means", "moreover", "mount", "municipal", "native", "nevertheless", "obesity",
    "offence", "outbreak", "o'clock", "poisonous", "pollution", "provincial", "punishment",
    "racial", "rat", "rifle", "robbery", "rural", "semester", "settler", "shooting", "shot",
    "soccer", "theif", "tsunami", "vulture", "weapon", "worldwide", "worthwhile", "execute",
    "drug",

    "load", "blast", "desire", "kiss", "brother", "sister", "mother", "fighting",
    "baby", "daughter", "girl", "teenager", "teenage", "trousers", "bleed", "touch"
]