export const includeWords = ["apollo", "hercules", "zeus", "atlas", "hermes", "mars", "saturn",
    "jupiter", "venus", "mercury", "pluto", "neptune", "violet", "indigo", "blue", "green",
    "yellow", "orange", "gold", "silver", "bronze", "iron", "sodium", "potassium", "magnesium",
    "calcium", "radium", "tin", "chromium", "zinc", "copper", "nickel", "cobalt", "odin", "thor",
    "basilisk", "centaur", "cyclops", "pegasus", "minotaur", "zodiac", "gemini", "lion",
    "scorpion", "aquarius", "capricorn", "goat", "voyager", "curiosity", "galileo", "grail",
    "hubble", "juno", "lunar", "solar", "shuttle", "viking", "electron", "photon", "neutron",
    "atom", "molecule", "euclid", "archimedes", "newton", "einstein", "darwin", "pascal", "tesla",
    "aristotle", "franklin", "babbage", "morse", "braille", "maxwell", "edison", "turing", "homer",
    "doyle", "shakespeare", "dante", "joyce", "byron", "milton", "voltaire", "huxley", "kipling",
    "shelley", "blake", "virgil", "auden", "keats", "beckett", "marlowe", "lawrence", "tennyson",
    "whitman", "yeats", "tolstoy", "beethoven", "vivaldi", "leonardo", "raphael", "michelangelo",
    "donatello", "genesis", "exodus", "camelot", "merlin", "grail", "backgammon", "checkers",
    "othello", "ludo", "monopoly", "alias", "labyrinth", "rummy", "mahjong", "mancala",
    "cribbage", "pontoon", "tag", "sardines", "conkers", "marbles", "tennis", "hopscotch", "limbo",
    "archery", "badminton", "cricket", "scooter", "surfing", "frisbee", "quidditch",
    "bouldering", "hiking", "judo", "karate", "ninja", "sumo", "fencing", "billiards", "snooker",
    "darts", "equestrian", "polo", "golf", "gymnastics", "juggling", "acrobatics", "skating",
    "triathlon", "decathalon", "marathon", "sprint", "hurdles", "bobsleigh", "toboggan", "hockey",
    "curling", "parkour", "walking", "omaha", "dominoes", "savior", "somehow", "turning",
    "romeo", "juliet",
    "briar", "macbeth", "boxer", "comet", "eureka", "excursion", "medusa", "hexagon",
    "pentagon", "virgo", "juniper", "omega",
    "prism", "portal", "rover", "utopia",
    "flamingo", "bonnet", "butler", "brahms", "waverly", "baron", "lamb", "marcel",
    "premises",
    "sycamore", "birch", "cinnamon", "daisy", "fennel", "fern", "fig", "harlequin", "holly",
    "honesty", "ivy", "jasmine", "maize", "maple", "mulberry", "parsley", "saffron", "thistle",
    "willow", "basil", "celery", "dill", "lavender", "licorice", "mustard", "oregano", "paprika",
    "poppy", "tarragon", "cress", "elf",  "hydra", "genie", "raven", "santa",
    "titan", "unicorn", "yeti", "alchemy", "alpha", "ace", "aqueduct", "astra", "bison", "blink",
    "shield", "campbell", "calypso", "cardinal", "carter", "challenger", "charcoal",
    "cloak", "colossus", "condor", "cooper", "crucible", "cyber", "jefferson", "dazzle", "destiny", "carlton",
    "celestial", "elixir", "equinox", "finesse", "flint", "flux", "fusion", "gambit", "gazelle",
    "griffin", "guardian", "hermit", "harker", "haven", "hemingway", "hudson", "amber", "icarus", "inertia",
    "infinite", "infinity", "jack", "jade", "jarvis", "jolt", "jones", "jubilee", "jude", "kale",
    "karma", "kestrel", "eric", "jake", "lark", "morgan", "monolith", "nathan", "andrew", "sanctity",
    "marconi", "matador", "module", "marvel", "marvellous", "oracle", "owl", "prodigy", "quasar", "quill",
    "jordan", "radius", "regent", "scramble", "scribe", "sentry", "samurai", "jasper", "solomon",
    "stark", "steed", "strobe", "tarzan", "termite", "ruby", "emerald", "turbo",
    "warren", "calculus", "geometry", "fibonacci", "hamilton", "pythagorus", "sculptor",
    "sombrero", "beret", "bowler", "fez", "trilby", "barley", "millet", "rye", "cider", "ginger",
    "plums", "lager", "sherry", "champagne", "sangria", "brandy", "whisk", "bourbon", "schnapps",
    "absinthe", "flock", "drove", "hive", "caravan", "kennel", "brace", "clan", "bloom",
    "raft", "rafter", "zeal", "vowel", "talisman", "julius", "logan", "magnet", "nylon", "maroon",
    "lime", "coral", "linen", "misty", "tan", "teal", "newt", "springer", "polaris",
    "trillion", "periodic", "lithium", "argon", "dalmatian", "spaniel", "mastiff", "bingo", "vista", "panorama",
    "chevron", "opal", "pearl", "sapphire", "beacon", "shamrock", "canteen", "fizz", "mason", "morris",
    "keg", "vase", "alpine", "fulcrum", "pivot", "cashmere", "merino", "satin", "suede", "tweed",
    "velvet", "flannel", "disco", "iconic", "beetroot", "dandelion",  "grape", "lettuce", "mini", "lucid",
    "turnip", "spinach", "melon", "pumpkin", "squash", "gherkin", "asparagus", "chives", "parsnip", "ford",
    "tiffany", "rex", "napoleon", "tabby", "collie", "husky", "beagle", "whippet", "corgi", "retriever",
    "dingo", "porcelain", "ceramic", "pug", "granite", "obsidian", "pumice", "grit", "slate", "nova",
    "aston", "dodge", "fiat", "wanderer", "mirth", "jewel", "hilarity", "glee", "ripple",
    "toffee", "crunch", "faithful", "slab", "pistachio", "safari", "sublime", "twirl", "hazel", "pecan",
    "pine", "custard", "malt", "molten", "tiffin", "sesame", "spice", "wafer",
    "marzipan", "nugget", "gum", "truffle", "cordial", "ribbon", "fondant", "glaze", "macaroon", "lozenge",
    "bouquet", "cookie", "caramel", "profiterole", "tiramisu", "syrup", "pastry", "fried", "baked", "sorbet",
    "strudel", "lattice", "pastels", "pretzel", "toaster", "banoffee", "cobbler", "treacle", "rhubarb", "persimmon",
    "pavlova", "bagel", "soda", "omelette", "porridge", "oasis", "kindling", "martini", "positioning", "madison",
    "garfield", "chester", "calvin", "hoover", "pal", "uber", "brook", "duke", "earl", "nautical",
    "octave", "pringle", "replay", "retro", "stance", "nirvana", "cranberry", "counting", "delta",
    "okay", "tv", "congregate", "loki", "sudoku", "mileage", "aspirin"]

export const excludeWords = ["virus", "pregnant", "hunger", "clown", "ape", "genocide",
    "nonetheless", "north", "south", "east", "west", "acceptable", "acid", "activation", "adult",
    "adverse", "aesthetic", "albeit", "allege", "attorney", "auto", "bacteria", "battlefield",
    "bean", "believe", "besides", "blonde", "blood", "bottom", "boyfriend", "girlfriend", "breast",
    "bug", "bullet", "CD", "DVD", "chemical", "chronic", "cigarette", "come", "communist",
    "conscience", "convict", "countless", "countryside", "creep", "crude", "cult", "deadly",
    "democracy", "democratic", "dependence", "depression", "devil", "donkey", "app", "earring",
    "eliminate", "empire", "emission", "epidemic", "examination", "explode", "extremist", "faction",
    "false", "fatal", "fault", "finger", "firearm", "foreigner", "foreign", "frog", "grab",
    "harassment", "ID", "infection", "injure", "inmate", "insert", "intimate", "invade", "martial",
    "master", "means", "moreover", "mount", "municipal", "native", "nevertheless", "obesity",
    "offence", "outbreak", "o'clock", "poisonous", "pollution", "provincial", "punishment",
    "racial", "rat", "rifle", "robbery", "rural", "semester", "settler", "shooting", "shot",
    "soccer", "theif", "tsunami", "vulture", "weapon", "worldwide", "worthwhile", "execute",
    "drug",

    "load", "blast", "desire", "kiss", "brother", "sister", "mother", "fighting",
    "baby", "daughter", "girl", "teenager", "teenage", "trousers", "bleed", "touch",

    "fragile", "beef", "bury", "bent", "wife", "burial", "lay", "meantime",

    "premise",

    "abolish", "absurd", "accordance", "achieve", "achievement", "acquisition", "acute", "adequate",
    "adhere", "adolescent", "affair", "affordable", "against", "aged", "alter", "amateur", "and",
    "April", "as", "assault", "asylum", "at", "attractive", "aunt", "August", "basic", "basketball",
    "bathroom", "beast", "beat", "behaviour", "blow", "bookshelf", "box", "boy", "broccoli", "capitalist",
    "castle", "cathedral", "centre", "chairman", "charge", "chase", "chemistry", "chest", "chicken", "chop", "church", "clerk",
    "colourful", "companion", "conceive", "conception", "congregation", "conquer", "consent", "conservative",
    "controversy", "conversion", "convert", "conviction", "course", "cream", "damaging", "dangerous", "date", "December",
    "deck", "deed", "deep", "defence", "defensive", "deficiency", "delight", "delivery", "deployment",
    "deprive", "desirable", "deteriorate", "disability", "disc", "discharge", "dominant", "dominate",
    "drought", "easy", "enjoy", "enquiry", "ensue", "exile", "explicit", "exploitation", "explosion",
    "explosive", "fantasy", "fat", "February", "female", "fever", "finish", "firefighter", "flavour", "flaw",
    "flawed", "flee", "floor", "fluid", "foot", "for", "force", "formation", "Friday", "from", "gas", "gaze",
    "grasp", "grip", "grow", "growth", "guest", "hail", "hand", "handful", "handle", "handy", "happy",
    "head", "headache", "healthcare", "helmet", "hence", "homeless", "homework", "honour", "horn", "huge",
    "hunt", "husband", "imagery", "imminent", "imprison", "imprisonment", "incorrect", "in", "independent",
    "indictment", "indigenous", "indulge", "industrial", "infant", "infect", "inflict", "innocent", "insertion",
    "inside", "interfere", "interference", "into", "its", "it", "jail", "January", "jeans", "July", "June",
    "kick", "kidnap", "knife", "lady", "lap", "last", "latter", "lead", "leg", "lesser", "liable", "lie", "lip",
    "love", "mainland", "mainstream", "marine", "marry", "massacre", "massive", "mate", "mature", "meat",
    "medieval", "member", "memorial", "mental", "mere", "merely", "metre", "mob", "mobilize", "model", "mom",
    "Monday", "monster", "mum", "nail", "nation", "nightmare", "norm", "November", "nurse", "nursing", "nut",
    "obsession", "occupation", "occupy", "officer", "oil", "OK", "ongoing", "online", "onto", "oppose",
    "opponent", "oral", "oragnize", "out", "over", "package", "pad", "painful", "pair", "passage", "passion",
    "passionate", "peasant", "period", "pig", "pit", "please", "pleasure", "postcard", "pound", "premise", "pregnancy",
    "priest", "proposition", "psychiatric", "pump", "punch", "punk", "purple", "pursue", "raw", "realization", "realize", "rear",
    "rebel", "red", "relationship", "release", "relief", "relieve", "reporduce", "reproduction", "republic", "residue",
    "reveal", "revolution", "rhythm", "ride", "rod", "romance", "romantic", "rough", "rub", "rubber", "satisfy", "Saturday",
    "sauce", "scissor", "score", "seed", "seize", "September", "serve", "service", "show", "sixteen", "skin",
    "skirt", "slap", "slice", "slide", "slip", "sloth", "snake", "spread", "stiff", "stream", "Sunday", "symptom",
    "T-shirt", "tail", "take", "talent", "tank", "target", "theirs", "thief", "throat", "tight", "tiny", "tip",
    "tube", "Tuesday", "under", "unnecessary", "up", "urge", "use", "user", "vacant", "veteran", "virtue",
    "ward", "warehouse", "warrior", "weaken", "Wednesday", "wet", "whip", "widow", "within", "work", "worm", "wrench", "yield",
    "activist", "less", "minimize", "October", "organize", "queen", "reproduce", "valley", "wood"
]

